name: Deploy Doxygen to Pages

# Runs on pushes targeting the default branch
on:
  push:
    branches: [master]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: build
      uses: mattnotmitt/doxygen-action@1.9.8
      with:
        working-directory: './docs/'
        doxyfile-path: 'docs/Doxyfile'

    - id: deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.MY_TOKEN }}
        publish_dir: './docs/build/html'

